name: Update gist
on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main  
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:  
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: ${{ secrets.Anything.. }}
          TIMEZONE: Asia/Seoul
  
